### ISSUE TITLE
OSError when launching ./fromage.py

### ISSUE THREAD

**Issue by arthurlutz** [yourcelf/btb#8]
(venv)arthur@machine:~/local/btb/btb/scanblog$ ./fromage.py 
/home/arthur/local/btb/venv/local/lib/python2.7/site-packages/djcelery/loaders.py:80: UserWarning: Using settings.DEBUG leads to a memory leak, neveruse this setting in production environments!
  warnings.warn("Using settings.DEBUG leads to a memory leak, never"
Traceback (most recent call last):
  File "/home/arthur/local/btb/btb/scanblog/manage.py", line 11, in <module>
    execute_manager(settings)
  File "/home/arthur/local/btb/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/home/arthur/local/btb/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/arthur/local/btb/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/arthur/local/btb/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/arthur/local/btb/btb/scanblog/btb/management/commands/autocompile.py", line 38, in handle
    self.autocompile()
  File "/home/arthur/local/btb/btb/scanblog/btb/management/commands/autocompile.py", line 27, in autocompile
    compass = self.exec_compass()
  File "/home/arthur/local/btb/btb/scanblog/btb/management/commands/autocompile.py", line 24, in exec_compass
    return subprocess.Popen(["compass", "watch"], cwd=SASS_PATH)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1239, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2012-03-30 09:27:36,980: WARNING/MainProcess]  

 -------------- celery@machine v2.2.10
---- **** -----
--- * ***  * -- [Configuration]
-- * - **** ---   . broker:      amqp://guest@localhost:5672//
- ** ----------   . loader:      djcelery.loaders.DjangoLoader
- ** ----------   . logfile:     [stderr]@WARNING
- ** ----------   . concurrency: 2
- ** ----------   . events:      OFF
- *** --- * ---   . beat:        OFF
-- ******* ----
--- ***** ----- [Queues]
 --------------   . celery:      exchange:celery (direct) binding:celery
                  

[2012-03-30 09:27:37,016: WARNING/MainProcess] celery@machine has started.

**Comment by yourcelf** [comment]
Obviated by the long ago change to ``django-compressor``.
